# Copyright 2020 Google, LLC.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Build and Deploy to Google Compute Engine without Docker

on:
  push:
    branches:
    - main
    - test-undetected-chrome

env:
  PROJECT_ID: ${{ secrets.GCE_PROJECT }}
  GCE_INSTANCE: gce-githubactions-nodocker-vm  # TODO: update to instance name
  GCE_INSTANCE_ZONE: us-west1-a    # TODO: update to instance zone

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-18.04
    #was  ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # Setup gcloud CLI
    - uses: google-github-actions/setup-gcloud@master
      with:
        version: '290.0.1'
        service_account_key: ${{ secrets.GCE_SA_KEY }}
        project_id: ${{ secrets.GCE_PROJECT }}

    - name: Deploy
      run: |-
        gcloud compute instances create "$GCE_INSTANCE" \
        --zone "$GCE_INSTANCE_ZONE" \
        --machine-type "e2-micro" \
        --metadata-from-file startup-script=bootscript.sh \
        --image=ubuntu-2110-impish-v20211014 \
        --image-project=ubuntu-os-cloud \
        --maintenance-policy=MIGRATE \
        --scopes=https://www.googleapis.com/auth/datastore,https://www.googleapis.com/auth/servicecontrol,https://www.googleapis.com/auth/service.management.readonly,https://www.googleapis.com/auth/logging.write,https://www.googleapis.com/auth/monitoring.write,https://www.googleapis.com/auth/trace.append,https://www.googleapis.com/auth/devstorage.write_only \
      # --service-account=xxxxxxx@developer.gserviceaccount.com \



        

      # gcloud compute instances update-container "$GCE_INSTANCE" \
      # --zone "$GCE_INSTANCE_ZONE" \
      # --container-image "gcr.io/$PROJECT_ID/$GCE_INSTANCE-image:$GITHUB_SHA"


  #  gcloud compute instances create-with-container "$GCE_INSTANCE" \
  #  --zone "$GCE_INSTANCE_ZONE" \
  # --machine-type "e2-micro" \
  # --container-image "gcr.io/$PROJECT_ID/$GCE_INSTANCE-image:$GITHUB_SHA"


#   Message: unknown error: cannot find Chrome binary
#   (Driver info: chromedriver=93.0.4577.63 (ff5c0da2ec0adeaed5550e6c7e98417dac77d98a-refs/branch-heads/4577@{#1135})
# ,platform=Linux 5.4.0-1051-gcp x86_64)